export const Trampoline = {
	themeFile: "clips/trampoline/theme_1_80.mp3",
	themeVolume: 1,
	endFile: 'clips/trampoline/end.mp3',
	firstDrawing: "drawings/trampoline/drive.json",
	firstSides: [0,1,4,5],
	lastDrawing: "drawings/trampoline/liens.json",
	lastSides: [0,1,4,5],
	dialogs: [
		{ track: "clips/trampoline/1.mp3",	 anim: "drawings/trampoline/city.json", 
			sides: [0, 1, 4, 5], 
			delay: 4000, end: 4000 },
		{ track: "clips/trampoline/2.mp3",	 anim: "drawings/trampoline/drive.json", 
			sides: [0,1, 4, 5], 
			delay: 4000, end: 3000 },
		{ track: "clips/trampoline/3.mp3",	 anim: "drawings/trampoline/woods.json", 
			sides: [0, 1, 4, 5], 
			delay: 3000, end: 3000},
		{ track: "clips/trampoline/4.mp3",	 anim: "drawings/trampoline/tramp.json", 
			sides: [0, 1, 3, 4, 5], 
			delay: 3000, end: 4000 },
		{ track: "clips/trampoline/5.mp3",  anim: "drawings/trampoline/hiding.json", 
			sides: [0, 1, 4, 5], 
			delay: 3000, end: 5000 },
		{ track: "clips/trampoline/6.mp3",	 anim: "drawings/trampoline/bounce_w_action_lines.json", 
			sides: [0, 1, 4, 5], 
			delay: 3000, end: 3000 },
		{ track: "clips/trampoline/7.mp3",	 anim: "drawings/trampoline/weight.json", 
			sides: [3], 
			delay: 7000, end: 3000 },
		{ track: "clips/trampoline/8.mp3",	 anim: "drawings/trampoline/shadow.json", 
			sides: [3], 
			delay: 3000, end: 4000 },
		{ track: "clips/trampoline/9.mp3",	 anim: "drawings/trampoline/woman_w_eyes.json", 
			sides: [0, 1, 4, 5], 
			delay: 3000, end: 3000 },
		{ track: "clips/trampoline/10.mp3", anim: "drawings/trampoline/house.json", 
			sides: [0, 1, 2, 3, 4, 5], 
			delay: 3000, end: 3000 },
		{ track: "clips/trampoline/11.mp3", anim: "drawings/trampoline/froze.json", 
			sides: [0, 1, 4, 5], 
			delay: 5000, end: 3000 },
		{ track: "clips/trampoline/12.mp3", anim: "drawings/trampoline/church.json", 
			sides: [0, 1], 
			delay: 3000, end: 7000 },
		{ track: "clips/trampoline/13.mp3", anim: "drawings/trampoline/hell.json", 
			sides: [0, 1, 2, 3, 4, 5], 
			delay: 3000, end: 5000 },
		{ track: "clips/trampoline/14.mp3", anim: "drawings/trampoline/liens.json", 
			sides: [0, 1, 4, 5], 
			delay: 3000, end: 5000 },
		{ track: "clips/trampoline/15.mp3", anim: "drawings/trampoline/augustine.json", 
			sides: [0, 1, 4], 
			delay: 3000, end: 5000 },
		{ track: "clips/trampoline/16.mp3", anim: "drawings/trampoline/red_lines.json", 
			sides: [0,1,2,3,4,5], 
			delay: 3000, end: 5000 }
	],
	model: "models/hotdogs/char_toon.gltf",
	durations: { 
		'Idle - 3 - Lying Down': 45,
		'Idle - 4 - Shaking': 41,
		'Idle - 6 - Carwheel': 	110,
		'Idle - 7 - Fall': 133,
		'Idle - 8 - Explode': 11,
		'Walk  - 1': 40,
		'Walk - 2': 40,
		'Walk - 3': 40,
		'Walk - 4': 40,
		'Talk - 3': 32,
		'Talk - 4': 27,
		'Talk - 5': 45,
		'Talk - 7': 45,
		'Talk - 8': 103
	},
	types: {
		idle: ['Idle - 3 - Lying Down', 'Idle - 4 - Shaking', 'Idle - 6 - Carwheel', 'Idle - 7 - Fall', 'Idle - 8 - Explode'],
		walk: ['Walk  - 1', 'Walk - 2', 'Walk - 3', 'Walk - 4'],
		talk: ['Talk - 3', 'Talk - 4', 'Talk - 5', 'Talk - 7', 'Talk - 8']
	},
	charSpeed: { min: 0.2, max: 0.3 },
	cameraSpeed: 0,
	camera: {
		speed: { x: 0, y: 0, z: 0},
		position: { x: 0, y: -1.5, z: 2.5}
	},
	charPosition: { x: 0, y: -5, z: -2 },
	androidPosition: { x: 2, y: -5, z: 2 },
	startIndex: 1,
	endAnim: [3, 6, 8],
	lookChance: 0
};